### PR TITLE
Merge release-0.4.1 branch to develop and add tags-feature

### LINKED ISSUE #624: Introduce #TAGS Attribute
##Suggestion
- Introduce `#TAGS` Attribute in Song Parser
- should have multiple entries see #623
- This field is for any reasonable keyword that fits to the song
- Songs should be categorized by #TAGS like #GENRE

(according to [official common Song format Specification](https://usdx.eu/format/) v1.1.0 - release on: 1th Dec 2023)

### LINKED ISSUE #633: Implement UTF-8 (without BOM) encoding support
## Suggestion
Introduce UTF-8 (Without BOM) Encoding for song textfiles as standard/default. Right now Vocaluxe only support UTF-8 (with BOM).

## Why?

- UTF-8 (without BOM) is the only allowed encoding according to [offical ultrastar song format specification](https://usdx.eu/format/). This is to end all encoding problems that heavily reduce user acceptance.
- CP encodings will be not possible in future in USDB.animux UTF-8 (without BOM) will be download standard in USDB and USDB SYNCER. All Song Editors agreed to UTF-8 (without BOM) as standard as well.
- All other games support UTF-8 (without BOM) Encoding
- This will highly improve acceptance of vocaluxe
- User can update collections from CP encoding to UTF-8 (Without BOM) via mass operation in UltraStar Manager.
- Developers don't have the problem to implement automatic guessing of encoding

Additional Info:
vocaluxe is the only game that doesn't handle UTF-8 (Without BOM) at the moment
encoding-confusion

### PR DESCRIPTION
**Pull request by flokuep**
Note: Haven't noticed, that the develop-branch wasn't up-to-date with the latest main-branch, so things got a bit messed... Sorry for that.

This will
- merge fixes of release 0.4.1 to develop branch
- set default encoding to utf-8
- add reading of new tag 'tags' (see #624)

Unfortunately, I don't have the possibility to do some tests on my own.

### CODE REVIEW

**Comment by marwin89** [comment]
I have some time for testing the next week. but I don't know how to get a test build (with this pr) :)

**Comment by flokuep** [comment]
You can find them by clicking on the appveyor-integration urls: https://ci.appveyor.com/project/VocaluxeBuildBot/vocaluxe/builds/48859090/job/7rr86pbr3geray12/artifacts

**Comment by marwin89** [comment]
Tested on Windows 10:
- fixes of release 0.4.1 are included in develop branch ✅ 
- default encoding is utf-8 ✅ 
- new tag 'tags' works fine in song screen (Str+7)/option screen/party modes ✅ 
- just translation of "Tags"-Feature has to be done ⚠️ 
Vocaluxe-QA-630-01
Vocaluxe-QA-630-02

**Comment by flokuep** [comment]
Good catch! I've changed it, can you please re-check? https://ci.appveyor.com/api/buildjobs/sc9bwh8oo6vfaiyc/artifacts/Vocaluxe_develop_Windows_x64.zip

**Review by marwin89 — CHANGES_REQUESTED** [review]
Looks good in option menu ✔️
Could you add in en.xml the following line: ?

```html
<string name="TR_SCREENSONG_NOTAGS">No Tags</string>
```

**Review by marwin89 — CHANGES_REQUESTED** [review]
There is a small typo here, "r" is missing 🙂 ✍🏻 
Vocaluxe-QA-630-03

**Comment by marwin89** [comment]
Looks good just two small requested changes 👍🏻

**Comment by flokuep** [comment]
Thanks :) Fixed!

**Review by marwin89 — APPROVED** [review]
👍🏻 🙂

**Pull request merged**
