### PR TITLE
New README

### PR DESCRIPTION
**Pull request by lukeIam**
Just as a suggestion that could be improved.

The old readme had some outdated info and wrong links

### CODE REVIEW

**Comment by derivator** [comment]
:+1: Merge.

**Comment by lukeIam** [comment]
Should we mention the (web)app, maybe with beta flag?

**Comment by flokuep** [comment]
Yes, I think the webapp is a nice feature, so we could mention it. Also our support for different party modes

**Comment by lukeIam** [comment]
@flokuep 
```
Vocaluxe offers diversified party modes and can optionally be controlled via Browser/App.
```
Do you have a better suggestion?

**Comment by flokuep** [comment]
No, its okay. +1

**Comment by lukeIam** [comment]
Everything you mentioned so far is changed...

**Pull request merged**
