### PR TITLE
Fix: Crash after starting a second challenge mode #169

### PR DESCRIPTION
**Pull request by z3ro01**

### CODE REVIEW

**Comment by flokuep** [comment]
Thanks for splitting up your commits to branches and specially for this fix. Looks fine to me. :+1:

**Comment by lukeIam** [comment]
No crash anymore - good!

But I'm experiencing an other behavior:
- I do have two songs in my Library.
- Start a challenge mode game (2 Players 1 Round)
- Exit the game after it has finished (song could be aborted)
- Start a new challenge mode game (2 Players 1 Round)
- There is **only one song visible** to choose (those which was not played in the first game)
- Exit the game after it has finished (song could be aborted)
- Start a new challenge mode game (2 Players 1 Round)
- There are two visible song again

I do not play the challenge mode - Is this a wanted behavior?

**Comment by flokuep** [comment]
In general: yes. If you play partymodes several times, you don't have same Songs again and again. But yeah, we maybe should only do this if there are more than 10 (?) Songs...

**Comment by lukeIam** [comment]
> In general: yes.

Ok then it is ok - It definitely makes sense...
I just thought new game - everything back to start.

> But yeah, we maybe should only do this if there are more than 10 (?) Songs...

Would be an option - but I don't think that there are may players with so few songs out there :wink: 

For the PR: good for me :+1:

**Pull request merged**
