### PR TITLE
Multi-monitor - Initial Support - Work in Progress

### PR DESCRIPTION
**Pull request by Jiiniasu**
Hello,

I've been tinkering with some kind of initial support for multi-monitor setups. The maximum amount of players is currently unchanged and the participating players will be spread across the available screens. This has been tested with both DirectX and OpenGL.

I am currently a bit annoyed by the fact that [ScreenSing.xml](https://github.com/Jiiniasu/Vocaluxe/blob/bf5205b08024cf266b79a6a9d5e938ff38f1d200/Output/Themes/Ambient/Screens/ScreenSing.xml) gets really inflated with the new elements for each screen. It would have been great if I was able to use the configuration for one screen and base the other elements of it in the code, but I didn't manage to figure out how it could be done without making it cough blood and die.

If anyone has got any idea on how this is done, I'd be happy to give it a shot.

What do you think of this feature and what can be improved in its current state?

I believe the next step would be upping the max players, aiming for up to 6x6 players. That would most likely be enough to satisfy the most. (Also, yes. 36 is a ridiculous amount of simultaneous players.) Will also have to figure out a good way of handling the amount of players in the game without sending the UX down the toilet. I have a few loose ideas in my mind, but would be nice to hear other ideas as well.

---
Mentioning #153 as this is relevant.

### CODE REVIEW

**Comment by flokuep** [comment]
Thanks for your work on this! Really like the idea of a 2nd screen for selecting songs etc. 

Regarding ScreenSing: I guess we could use the current (not changed) state of ScreenSing. You could add an option that says: Use all monitors for singing or Use less as possible monitors for singing. In initializing ScreenSong you need some logic, but basically you _copy_ all NoteBar informations to every screen and then set different visibiltys. There might be a little problem with player colors (uh, a big problem to find 36 different colors), but in general that could work.

Regarding 'real' multimonitor use: Quite don't know if this is a good and working solution, but just an idea to discuss: We could add some kind of monitor managment. On chaning screens, a method like 'showNextScreen(Screen) is currently called (name is not correct, but can't remeber, but it's there). MonitorManagment could step into this and handle some logic. There could be different modes: Cloning everything (show the same on every monitor, just singing and results is working different), Split-screen (or a better name). Last one would be useful for issue #153. If there are games in queue (game is song, song-mode, player [and game-mode), singing is possible and should start on a screen. The other screen could just work for selecting songs and players [we might need a new screen for controlling game-queue]. MonitorManagment would handle that every monitor shows the correct screen.

**Comment by Jiiniasu** [comment]
Maybe I should clarify that my primary intent with this change is to enable more simultaneous players. I don't see having a dedicated screen for other tasks to be of high priority as the web-interface has the potential of letting other devices do the job against the host running the game. (Also trying to not bite off more than I can chew... =P)

As the code in my branch is set up now, everything defaults to being shown on all screens. The notes and player statics/texts are set to only be shown once, on one screen. So I guess it's similarily functioning like multiscreen in UltraStar Deluxe, but with a slightly different way of distributing players (I think).

(Screenshots below for those who just want to see how it can look like without compiling the thing)
vocabrowse
fiveontwo

Regarding ScreenSing: 

I didn't manage to wrap my head around how the elements were created when etc during the weekend. Thought I'd be able to make copies of the elements when loaded from the xml and just alter the X-values accordingly for each screen but the way I tried to do it failed. I'll have to tinker with it a bit more.

Regarding colours:

Yes, finding 36 distinct colours would be impossible I believe. My current idea is to use the 6 distinct colours already available and make sure they only appear on each screen only once. As there can only be 6 players per screen, it wouldn't be unreasonable to cap it to a total of 12 players if 2 screens are used, and 18 for 3 screens and so on. If there are say, 8 players across 4 screens (This I have actually tested in a real session, although with my bodge-build.) we would have two blues, and two reds, but on different screens if we decide to use all 6 available distinct colours. Else it could as well be four blues and four reds.

To practically keep track of the multiple occurances of colours I was thinking that it might perhaps be a good idea to assign each screen a colour. So, blue-blue would be blue player on screen blue, red-blue would be blue player on screen red etc.

(Sorry if my post is slightly incoherent. Brain is tired.)

**Comment by lukeIam** [comment]
@Jiiniasu thanks for your work! 
BTW: Intel has also a surround feature called [Collage-Display](http://www.intel.de/content/www/de/de/support/graphics-drivers/000006547.html) and it works fine with your build.

There might be an other solution without driver functions: window mode + frameless window with borderstyle=None + window resolution=sum(screenRes) + render the real screen with screen and add the result the result image (at the right position) + black background + spawn the window at the left screen left upper corner
image
But I have to admit that this would be a bit hacky and not so easy to maintain. As AMD (Windows + Linux), nVidia (Windows + maybe Linux) and Intel (Windows) support this multimonitor feature I would say we can build on that.

I played a bit with you build and it looks good 👍 
But I couldn't test deep because with many players I get freezes (but also with the current beta #249).

Sadly I'm not very deep in Vocaluxe-UI-System-Stuff, but if I can help something please tell me.

**Comment by Jiiniasu** [comment]
@lukeIam In my previous attempt of multimonitor I spawned multiple windows in OpenGL that could be individually resized etc, but I abandoned that approach because I found it too complex to figure out how to do it properly. My implementation had a lot of context changes which led to a really slow and GPU intensive build.

Regarding the freezing: I haven't had any problems running the game with many players, although the debug build did lag a whole lot when running 8 players, but it tracked the tones from the mics without problems. Running the release build it was playing with smooth graphics. I've run 6-player games on my laptops without any noticable issues...

**Comment by flokuep** [comment]
I could tell you some more about ui-system, so just ask if there are any questions...

In general: Everything you put into _ThemeX-arrays, vocaluxe looks for these elements in screen-xml. I guess it could be a solutin to load 'old' screen-elements and then create copies of them for every screen. You could use e.g GetNewStatic() or GetNewStatic(existingStatic) for this task....

**Comment by Jiiniasu** [comment]
I've managed to trim the fat off the screensing.xml and added code that generates the elements for the other screens. Feedback very much appreciated!

**Comment by flokuep** [comment]
Looks quite better 👍 You might need to duplicate also StaticExtra and TextExtra for every screen...

**Comment by Jiiniasu** [comment]
@flokuep 
I've now made the necessary changes to show StaticExtra and TextExtra elements correctly.

If there aren't any bugs or other things I've missed I'd consider the initial support to be completed. I believe player expansion should come in a separate pull-request. What do you think?

**Comment by lukeIam** [comment]
> There might be a little problem with player colors (uh, a big problem to find 36 different colors), but in general that could work.

how about assigning icons to the microphones: e.g. instruments, animals, ...

**Review by flokuep — APPROVED** [review]
There is some reformatting I don't really like in merge requests, but it's okay for now.

Thanks for your work!

**Comment by flokuep** [comment]
This is a really nice step into multi-monitor support. @lukeIam I would like to merge this, so @Jiiniasu or somebody else could start working on supporting more player (or other multimonitor features?)

**Comment by Jiiniasu** [comment]
Just FYI, I've got a build that is playable with up to 36 players, but I've still got a lot of UI-work, bugfixing and code cleanup left to do...

**Comment by lukeIam** [comment]
> > but I've still got a lot of UI-work, bugfixing and code cleanup left to do on that...

> This is a really nice step into multi-monitor support. @lukeIam I would like to merge this, so @Jiiniasu or somebody else could start working on supporting more player (or other multimonitor features?)

I would love to see this live.
But are those open UI things and bugs affecting the the normal play (up to six players)? I thing the develop branch should stay in a working state (it's the base for other developments and for the nightlies)
If not I would vote for fixing the open points in this branch.

If there are multiple open issues, how about make a short list of these here - maybe we can help fixem them.

**Comment by flokuep** [comment]
Currently this branch is in a working state. You 'just' can increase number of monitors in config.xml. After that, they are displayed properly and while singing, vocaluxe tries to display player notes as big as possible (1 screen, 6 player: all on one; 2 screens, 6 player: 3 on 1, and so on)...

I guess this is a very good start. More additions/gameplay/whatever could be done in different pull-requests.

**Review by lukeIam — APPROVED** [review]
ok then also from my side: 👍

**Comment by flokuep** [comment]
@Jiiniasu Thanks for your work; If we could help you with adding stuff for a 'more than 6 player build', feel free to spread them ;)

**Comment by Jiiniasu** [comment]
@lukeIam If you want to to try out the 36-player build before I make a PR you can check out this branch:
https://github.com/Jiiniasu/Vocaluxe/tree/Multimonitor-More-Players

The player selection looks like shit and I'm still far from happy with the options > record-screen, but it works if you just want to try the ridiculous amount of players that is possible. I've so far "only" managed to test it out live with 16 players across 4 projectors. (It was a really fun experience!)

**Pull request merged**
