### PR TITLE
Version tag generation moved to build script

### PR DESCRIPTION
**Pull request by lukeIam**
see also #239
image

Does it makes sense to move tag generation to the build script (and making it a bit more complex) for:
- having the full version tag in the Application Details
- remove tag generation stuff from the c# code

the linux build script is just tested in a windows git bash.
@derivator or @flokuep can you may test this with your linux build environment?

### CODE REVIEW

**Comment by flokuep** [comment]
Looks nice. Currently, vocaluxe doesn't compile on my linux system... I have some problems with compiling ffmpeg.

**Comment by lukeIam** [comment]
> Currently, vocaluxe doesn't compile on my linux system... I have some problems with compiling ffmpeg.

This was also the point I gave up the last time...
I'll give it another try.

**Comment by lukeIam** [comment]
> Currently, vocaluxe doesn't compile on my linux system... I have some problems with compiling ffmpeg.
> >  This was also the point I gave up the last time...
> >  I'll give it another try.

After a lot of trial and error I got it compiling on travis. But there are still some runtime dependencies missing so I couldn't test the binaries (linux/ubuntu dependency management could be a real pain 😡 ).

Try to use this script to install ffmpeg:  https://github.com/lukeIam/Vocaluxe/blob/travis/.travis/installFFmpeg.sh

**Comment by flokuep** [comment]
@lukeIam Do you like to merge this before release of 0.4?

**Comment by lukeIam** [comment]
> @lukeIam <https://github.com/lukeiam> Do you like to merge this before
release of 0.4?

It would be nice to have proper version info in the file -> You can merge
this if you like
I will be at home ~17:00 to fix potential errors.

**Comment by lukeIam** [comment]
@flokuep the builds look good for me - did you observe something unusual?

**Comment by flokuep** [comment]
No. Everything is okay.

**Pull request merged**
