### PR TITLE
Updated credit screen

### PR DESCRIPTION
**Pull request by GRaff844**
The credits have been updated using the information from the Wiki (#676)
It's easier now to add, edit or delete any text shown on the screen

This serves as a basis for a designer to update the graphics and improve its visual appeal.

Here is a video showing the screen:
https://vimeo.com/1027728743

### CODE REVIEW

**Comment by marwin89** [comment]
@GRaff844 : Thank you, much appreciated! 🙂 
It would be awesome if you make the Background = "Themes/Vocaluxe 2024/BG_Video_4.mp4" and build in the new vocaluxe logo "Themes/Vocaluxe 2024/LogoMain.png". 

@flokuep: can you review the code?

**Comment by marwin89** [comment]
Good work! 👍🏻

**Review by flokuep — CHANGES_REQUESTED** [review]
Thanks for updating the credits screen :) I'm not sure if the list of translators is correct. We might switch to a more generic sentence here, like "Thank you to everyone translating Vocaluxe into different languages". @marwin89 what's your opinion on that?

**Comment by marwin89** [comment]
@flokuep : I agree. Let's do:

`Translation`
`Thanks to everyone translating Vocaluxe into different languages.`

The listed names were too old and don't represent the work of the last 5 Years. 
If when have a dedicated Translators team in future we can add such a list again. I'll update the credits page in wiki.

@GRaff844 could you change that? And could you make the background color just black? After that we merge it right away.

**Comment by GRaff844** [comment]
The color and text have been changed

**Review by flokuep — APPROVED** [review]

**Pull request merged**
