### PR TITLE
Full HD

### PR DESCRIPTION
**Pull request by ghost**
Render in Full HD, see #674 

-) Updated rendering resolution from 1280x720 to 1920x1080 for Full HD support.
-) Resized all screens to fit the new resolution.
-) Adjusted three default values to optimize for HD rendering.

### CODE REVIEW

**Comment by flokuep** [comment]
Great! Thank you. I'm a bit afraid of merging that directly, because I cannot oversee all possible implications right now. 

What have you done for tests to see if your implementation works? I'm thinking of
- different renders: Direct3D and OpenGL
- different background Videos with different solutions 
- screens with animations that might have some hard coded values inside the code, e.g. song selection, Highscores, ...

I'm personally without a windows system to do tests on my own, but I'll ask on discord. 

Nonetheless: The theme system is versioned, could you increase the theme system version and add a note to the change log file as this is a breaking change.

**Comment by ghost** [comment]
I have updated the Theme System Version and added notes to the changelog.

For testing, I completed the following steps (in addition to checking every screen):
-) Tested various video resolutions for both theme and song videos, including some non-standard resolutions.
-) Tested every game mode and song mode using different combinations of player counts.
-) All test were done with both renderers (D3D and OpenGL).

**Review by flokuep — APPROVED** [review]

**Comment by flokuep** [comment]
Sound very good, thank you :)

**Comment by marwin89** [comment]
@Rap-Voca , cool thanks for your contribution 😃

**Pull request merged**
