### PR TITLE
Fixes and new internal feature

### PR DESCRIPTION
**Pull request by z3ro01**
Fix crash in partymodes: If you play on any partymode, and game ended successfully, you cant start it again. Variables doesnt reset to their defaults and throws outofindex error.
New internal feature: I created a new type of popupscreen. Its perfect for confirm/alert/loading windows. You could call it from anywhere (including partymodes).  You can set up title/text/button labels, and button/key events with a callback. Medium and Big popups have scrollable text support with automatic line calculation. I modified test screen too, and add some test cases to it. If you press numeric keys (1-7) you could see some demo windows, and usage.

### CODE REVIEW

**Comment by lukeIam** [comment]
Hey @z3ro01,
I just discovered your PR...
As I like the idea of the popup screens I wanted to test them but I'm getting:
`The type or namespace name "CPopupScreenGeneral" could not be found (are you missing a using directive or an assembly reference?)` in https://github.com/Vocaluxe/Vocaluxe/pull/152/files#diff-c786150f732973e62687371a5ee625f4R91

**Comment by lukeIam** [comment]
Found a little bug in the popups with scrollable text:

* open a scrollable popup with more text than one page can contain
* click the `down button` till you reach the end
* click the `up button` till you reach the top
* click the (disabled) `up button` again -> the text will move down

**Comment by z3ro01** [comment]
I'm currently really busy. I have a new version, that can handle percentage loaders too.  
I will fix your bug and upload the new sources after 14th of Dec.

**Comment by flokuep** [comment]
If it's okay I would have a look on this and fix bugs, so we can merge it...

**Pull request closed without merging**
