### PR TITLE
Bugfix release 0.4.1

### PR DESCRIPTION
**Pull request by flokuep**
Please add more bugfixes for current released version 0.4 to release-0.4.1 branch. Just use this for having release-0.4.1 nightly ;)

### CODE REVIEW

**Comment by lukeIam** [comment]
Note: we should mot forget to merge all fixes (for still existing features) to develop when this ist closed.

**Comment by flokuep** [comment]
@lukeIam I would like to merge these changes into develop to have them in nightly...

**Comment by lukeIam** [comment]
> @lukeIam I would like to merge these changes into develop to have them in nightly...

@flokuep Are all of these changes apply-able to the current nightly?
If so we can merge, otherwise we have the cherry pick the right commits.

**Comment by flokuep** [comment]
> @flokuep Are all of these changes apply-able to the current nightly?
If so we can merge, otherwise we have the cherry pick the right commits.
Some minor merge conflicts. I've resolved them and pushed release-0.4.1 changes to develop...

**Pull request merged**
