### PR TITLE
Update CSongMenuList.cs to have the selected song in the middle of the list

### PR DESCRIPTION
**Pull request by Stefan1200-de**
Updated _UpdateList() to make sure, that the new selected song entry is in the middle of the visible song list.

### CODE REVIEW

**Comment by daggeg** [comment]
The new nightly build is that built on the last committed code in the develop branch + this new code?

**Comment by Stefan1200-de** [comment]
> The new nightly build is that built on the last committed code in the develop branch + this new code?

No, that is based on the release-0.4.1 branch, because I prefer that version instead of the new theme in the nightly.

**Comment by daggeg** [comment]
Ok, I like the genius theme much more and I don't seem to get that to work. I also see that it's an old version of challenge mode. I like what you've done but a working challenge mode is more important to me than coming back to the "right song" after having sung a song. Perhaps it's possible to implement this new code in the develop branch?

**Comment by Stefan1200-de** [comment]
> Perhaps it's possible to implement this new code in the develop branch as well?

Well, maybe another developer can do this. I don't want to start developing at the develop branch. I just did the two changes for me (and I just use version 0.4.1) and uploaded them, if the main developers come back someday and like my changes.

**Comment by daggeg** [comment]
Ok, thanks for the contribution.

**Comment by Stefan1200-de** [comment]
> Well, maybe another developer can do this. I don't want to start developing at the develop branch. I just did the two changes for me (and I just use version 0.4.1) and uploaded them, if the main developers come back someday and like my changes.

So fast things can change :D ;)
I guess I will add this for the development branch soon too. :)

**Comment by flokuep** [comment]
@Stefan1200-de Do you remember why you've added the do-not-merge label here? I'm currently sorting out PRs and would be happy to merge this into dev...

**Comment by flokuep** [comment]
> @Stefan1200-de Do you remember why you've added the do-not-merge label here? I'm currently sorting out PRs and would be happy to merge this into dev...

Oh, after updating to latest develop this seems to be merged already, so I guess we can close this.

**Comment by marwin89** [comment]
@flokuep can we close this PR now?

**Pull request closed without merging**
