### PR TITLE
Direct3d native fullscreen

### PR DESCRIPTION
**Pull request by lukeIam**
Add an option to use DirectX's full screen mode

### CODE REVIEW

**Review by flokuep — CHANGES_REQUESTED** [review]
Code looks good to me, but I've found a small bug (see seperate comment for more details)

**Comment by flokuep** [comment]
When I start Vocaluxe with enabled NativeFullScreen it looks like this:
bug
I need to switch to another window and then back to Vocaluxe to have a 'full' fullscreen. Switching to window mode and then back to fullscreen brings back wrong 'fullscreen size'.

Another _problem_: If you enable more than one screen, every screen gets stretched instead of showing black bars above and beyond. I guess this could be a problem when you have multiple screens with different resolutions?

And a small note: Could you rename _DirectX_ in conig comment to _Direct3D_? This matches better to renderer config...

Thanks for working on this.

**Comment by lukeIam** [comment]
> When I start Vocaluxe with enabled NativeFullScreen it looks like this:
> 
> I need to switch to another window and then back to Vocaluxe to have a 'full' fullscreen. Switching to window mode and then back to fullscreen brings back wrong 'fullscreen size'.

Interesting - for me its working for my Laptop screen and two other attached screens without any problem. By the way I haven't changed anything on the resizing algorithm.

> Another problem: If you enable more than one screen, every screen gets stretched instead of showing black bars above and beyond. I guess this could be a problem when you have multiple screens with different resolutions?

Haven't tired this. I don't know if a native full screen is possible on such a merged multi-display of differently sized screens.
I'll do some tests.

> And a small note: Could you rename DirectX in conig comment to Direct3D? This matches better to renderer config...

ok

**Comment by flokuep** [comment]
> Haven't tired this. I don't know if a native full screen is possible on such a merged multi-display of differently sized screens.
Good point, in this case we should maybe automatically set it to non-native fullscreen mode or do some logging in error.log?

**Comment by lukeIam** [comment]
> When I start Vocaluxe with enabled NativeFullScreen it looks like this:

Do you get this screen in fullscreen mode oder windowed mode? (can you "grab" the lower edges of the window) I can reproduce a similar misaligned view if I switch from fullscreen to windowed mode (with NativeFullScreen and without).

**Comment by lukeIam** [comment]
An other problem: if yo

- start the game in native fullscreen mode on monitor 1
- press 'Alt + Enter' (for window mode)
- move the window to a second monitor 2 (different resolution)
- press 'Alt + Enter' (for fullcreen mode again)
- Receive a crash: "Failed to reset the device" from D3D

**Comment by flokuep** [comment]
That's strange. I wanted to test it again and get this exception:
```Unhandled error: D3DERR_INVALIDCALL: Invalid call (-2005530516)   bei SlimDX.Result.Throw[T](Object dataKey, Object dataValue)
   bei SlimDX.Result.Record[T](Int32 hr, Boolean failed, Object dataKey, Object dataValue)
   bei SlimDX.Direct3D9.Device.Reset(PresentParameters[] presentParameters)
   bei Vocaluxe.Lib.Draw.CDirect3D._Reset()
   bei Vocaluxe.Lib.Draw.CDirect3D._EnterFullScreen()
   bei Vocaluxe.Lib.Draw.CDrawBase`1.MainLoop()
   bei Vocaluxe.Lib.Draw.CDrawBaseWindows`1.MainLoop()
   bei Vocaluxe.CMainProgram._Run(String[] args)
   bei Vocaluxe.CMainProgram.Main(String[] args)
```
Can't reproduce it, I didn't changed anything in config...

Regarding your question: I get this view in fullscreen mode.

**Comment by lukeIam** [comment]
I'm giving this an other try...

**Comment by lukeIam** [comment]
@flokuep can you test again?

**Comment by flokuep** [comment]
Still have this problem. When I'll start vocaluxe with fullscreen enabled, it looks like this:

error

I get the same when toggeling between fullscreen and none fullscreen-mode. When switching to another window and then back to vocaluxe window, everything looks right.

**Comment by lukeIam** [comment]
> Still have this problem.

Strange...
(I've tested with 3 screens with different Resolutions and aspect ratios and never got something like you...)

**Comment by lukeIam** [comment]
Can you please check the values of `_PresentParameters.BackBufferWidth`, `_PresentParameters.BackBufferHeight` and `_Device.Viewport` at:
- https://github.com/Vocaluxe/Vocaluxe/pull/334/files#diff-f6904e9ab088601177482ea6761c3dd1R256
- somewhere after the Alt+Tab

**Comment by flokuep** [comment]
Yes, of course.

Inside of EnterFullscreen:
`[00:00:04.1808525] [Error] BackBufferWidth: 2560
{ThreadId: 1, CallingContext: "{ callerMethodeName = _EnterFullScreen, callerFilePath = C:\Users\Florian\Git\Vocaluxe\Vocaluxe\Lib\Draw\CDirect3D.cs, callerLineNumer = 257 }"}
[00:00:04.1828187] [Error] BackBufferHeight: 1440
{ThreadId: 1, CallingContext: "{ callerMethodeName = _EnterFullScreen, callerFilePath = C:\Users\Florian\Git\Vocaluxe\Vocaluxe\Lib\Draw\CDirect3D.cs, callerLineNumer = 258 }"}
[00:00:04.1906863] [Error] DeviceViewportX:0 Y:0 Width:2560 Height:1440 MinZ:0 MaxZ:1
{ThreadId: 1, CallingContext: "{ callerMethodeName = _EnterFullScreen, callerFilePath = C:\Users\Florian\Git\Vocaluxe\Vocaluxe\Lib\Draw\CDirect3D.cs, callerLineNumer = 259 }"}`

After Alt + Tab:
`[00:00:08.8324742] [Error] BackBufferWidth: 2560
{ThreadId: 1, CallingContext: "{ callerMethodeName = _LeaveFullScreen, callerFilePath = C:\Users\Florian\Git\Vocaluxe\Vocaluxe\Lib\Draw\CDirect3D.cs, callerLineNumer = 265 }"}
[00:00:08.8324742] [Error] BackBufferHeight: 1440
{ThreadId: 1, CallingContext: "{ callerMethodeName = _LeaveFullScreen, callerFilePath = C:\Users\Florian\Git\Vocaluxe\Vocaluxe\Lib\Draw\CDirect3D.cs, callerLineNumer = 266 }"}
[00:00:08.8324742] [Error] DeviceViewportX:0 Y:0 Width:2560 Height:1440 MinZ:0 MaxZ:1
{ThreadId: 1, CallingContext: "{ callerMethodeName = _LeaveFullScreen, callerFilePath = C:\Users\Florian\Git\Vocaluxe\Vocaluxe\Lib\Draw\CDirect3D.cs, callerLineNumer = 267 }"}`

**Comment by lukeIam** [comment]
> Yes, of course.

Thanks! But it looks good... I'm a bit clueless atm...

**Comment by lukeIam** [comment]
> Maybe you could also set this in your settings and could reproduce it?

Can't reproduce it even with 125% display scaling.
(I only get a crash if I use 125% and the max display resolution)

> just a small gap at the bottom of window

I can get something like this (also with 125%):
image
But that is the window mode with the window title outside the upper screen bound.
If I use the taskbar icon to trigger the move command I can move it down.
Or `Alt + Enter` and I'm back in fullscreen mode without that gap.

**Comment by lukeIam** [comment]
if `alt + enter` does also not work, then I have no idea where to search next....

**Comment by marwin89** [comment]
I close this pr due inactivity after 6 years. Please re-open if needed.
It could be a helpful feature.

**Pull request closed without merging**
