### PR TITLE
Multimonitor more players

### PR DESCRIPTION
**Pull request by Jiiniasu**
Well, should be considered "wip" I guess, but since I haven't done much for this branch since 2017 I thought I might as well put a PR for whoever wants to carry this further considering the recent spike in activity.

This PR enables the full simultaneous 36 players and comes with a new mic config page. However I didn't manage to figure out a way to assign players which I was happy about, so right now it's just got all the elements put in to be "functional". (TBH I wasn't too happy with the mic config screen, but at least it gave a good overview when using/testing the silly amount of microphones it can handle)

### CODE REVIEW

**Comment by Stefan1200-de** [comment]
I look at this in the next days. Currently I work on some smaller changes, which I like to implement soon.

**Comment by Stefan1200-de** [comment]
I did a first look on your change. In my opinion on the record config screen, while you select a microphone for a player, the Back and Delay test button should be invisible, while the Cancel and Apply buttons are visible. I think that looks better and make the buttons better readable. Or what do you think?

image

Just a stupid question: Where you can use more than 6 players currently? Only at the challenge modes? But they are not singing at the same time, right?

**Comment by lukeIam** [comment]
> But they are not singing at the same time, right?

As far as I can remember they can sing at the same time :satisfied:

**Comment by Jiiniasu** [comment]
>In my opinion on the record config screen, while you select a microphone for a player, the Back and Delay test button should be invisible, while the Cancel and Apply buttons are visible.

I agree. 

> Just a stupid question: Where you can use more than 6 players currently? Only at the challenge modes? But they are not singing at the same time, right?

I'm not a fan at all of the challenge modes, so I have honestly little knowledge of them. I'd assume those modes only handle up to 6 simultaneous players depending on the game.

The raise to a 36 player cap is for the "normal" mode. It will limit to n * 6, where n is the amount of monitor set. So if you only have one monitor you will still be limited to 6 players, two monitors you can play up to 12 players, etc.

**Comment by Stefan1200-de** [comment]
> The raise to a 36 player cap is for the "normal" mode. It will limit to n * 6, where n is the amount of screens set (NumScreens in Config.xml) . So if you only have one screens you will still be limited to 6 players, two screens you can play up to 12 players, etc.

Okay, so I just changed the NumScreens value in the Config.xml to 2 (I also have two physical monitors) and started your branch. It looks really weird. Both screens was on one physical monitor (mirrored, not extended) and the player icons on the player selection screens overlaps, if I select more than 6 players (player 7 overlaps player 1, player 8 overlaps player 2, and so on).
image

That should be fixed before I can approve that pull request. If you need more information, just write me, which kind of information you need. I still have your build on my PC to provide more tests and stuff like that.

**Comment by Jiiniasu** [comment]
> if I select more than 6 players (player 7 overlaps player 1, player 8 overlaps player 2, and so on).
> [...]
> That should be fixed before I can approve that pull request.

Correct, this is what I meant with
> However I didn't manage to figure out a way to assign players which I was happy about, so right now it's just got all the elements put in to be "functional". 

I had some ideas, but I wasn't too happy with them. Examples below:

Playerselect_36
(mockup)

Screenshot_2
(from a different branch that had a test)

Screenshot_3
(from the same branch as above, but looks slightly more broken as I hadn't fixed the profile scroll buttons.)

If there are any good ideas on how to best solve the profile selection UI for 6+ players, I'm interested to hear and might try find time to get it in the branch to finish it off.

**Comment by Stefan1200-de** [comment]
I understand. I like your mockup, maybe with an added player count setting. I'm not very happy with the currently player selection of Vocaluxe, so almost everything would be an improvement. But it works and Vocaluxe has enough other stuff I can work on. ;)

My suggestion: The player selection could already make usage of multiple screens and show only 6 players per screen, which will also playing on that screen. Would that be possible? Or do I miss anything?

**Comment by Jiiniasu** [comment]
> My suggestion: The player selection could already make usage of multiple screens and show only 6 players per screen, which will also playing on that screen. Would that be possible? Or do I miss anything?

I've been thinking about that possibility, but I'm not sure if that would make good UX. With so many players it gets physically crowded in the room you're in and having to move ones attention between different monitors while maintaining reach for mouse/keyboard might be too cumbersome if the screens are large and far apart.

However showing the assigned players on each respective screen might be a good feature to help keep track of who is assignd where though.

I'm thinking maybe a setup as in the second image, but with a y-axis scroll for the selected profiles is a good compromise in this case... I'd assume most people who play the game set their profile once and leave it for the entire session (if there are enough mics for everybody). If my assumption is correct then this would probably be good enough. It would be nice with some sort of data on the common behaviour though. How many profile changes do you do?

In my usecase there are a lot of different people playing and a lot of profile swaps are "required" for it to be correct. Not uncommon to swap out half of the players after a song. For my heavily modded branch I've "solved" this conundrum by completely removing the profile assignment from the game UI and instead I've given each player a small touchscreen where they can select their profile via a browser. That's so far the only way I've managed to get 12 people to use the correct profiles when playing the game instead of just going with whatever is already selected due to impatience/laziness. This specific solution is most likely impractical for the masses, but might be an interesting feature to build on to the webserver in the future.

0F0A8951
(Picture of the most recent Vocaluxe setup I used for those who are curious)

**Comment by Stefan1200-de** [comment]
Wow, never saw such big environments. Looks amazing. I only play Vocaluxe in smaller max 3 player environments, most time just with guest profiles. So I can't really say what the best usability would be.

**Comment by daggeg** [comment]
Wow! Which university, KTH?

**Comment by Jiiniasu** [comment]
> I only play Vocaluxe in smaller max 3 player environments, most time just with guest profiles.
Ah, then I suppose there's not much profile switching needed in your case. Is there a reason you tend to use guest profiles?

> Which university, KTH?
Actually not a university, but it was indeed set up in a school - for the students' enjoyment and inspiration.

**Comment by Stefan1200-de** [comment]
> Ah, then I suppose there's not much profile switching needed in your case. Is there a reason you tend to use guest profiles?

Never think about it before. Also I use Vocaluxe on three different PCs, I guess I can't share highscores without changing the path to OneDrive ;)

**Comment by daggeg** [comment]
> > I only play Vocaluxe in smaller max 3 player environments, most time just with guest profiles.
> 
> Ah, then I suppose there's not much profile switching needed in your case. Is there a reason you tend to use guest profiles?

We never let anyone use guest profiles at our house. The highscore lists is such an integral part of the game. We've got 13,000 entries in the highscore database :)

> > Which university, KTH?
> 
> Actually not a university, but it was indeed set up in a school - for the students' enjoyment and inspiration.

It kind of looked like KTH when I was studying there in the first half of the 90:s :) Nevertheless, so cool that you have the facilities to pull that off. We've never had more than 20 people over playing the game and six mics have always worked very well since people tend to enjoy watching/singing along in the background. Especially when compete in teams.

**Comment by metinc** [comment]
@Jiiniasu This looks amazing. Why was the PR closed?

**Comment by Jiiniasu** [comment]
> @Jiiniasu This looks amazing. Why was the PR closed?

Hi,
I closed it as the branch got stale and outdated while a general cleanup was being done on the repo at the time.

The theme I had made also got swapped and purged so a lot has to be done from scratch anyway.

**Pull request closed without merging**
