### PR TITLE
Wiimote single thread experiment

### PR DESCRIPTION
**Pull request by lukeIam**
Removes one out of the threads from the Wiimote handler.
One thread is just waiting that the other changes something -> introduced an event

I can not test this, but I think @Shiroi has tested it.
@Shiroi: can you please confirm...

### CODE REVIEW

**Comment by Shiroi** [comment]
Just tested it again and the commit is working (on Win7). Wiimote is found and can be used to control Vocaluxe.

**Comment by flokuep** [comment]
Okay, I guess we could merge then? :+1:

**Comment by Shiroi** [comment]
:+1: for merging

**Comment by lukeIam** [comment]
Thanks!

**Pull request merged**
