### PR TITLE
Genius-Theme as Default

### PR DESCRIPTION
**Pull request by Jiiniasu**
Hello,
In response to #245 I've made a branch where the Ambient theme has been replaced with the Genius theme I've made. I have also updated to the most recent version of Genius I had in store.

What do you think? Any improvements suggestions?

### CODE REVIEW

**Comment by flokuep** [comment]
Wow! Really beautiful :) Thanks for this!

**Comment by derivator** [comment]
It does look quite nice, but I've also grown quite fond of the way Ambient looks... supporting both would be more work I guess, but maybe it's worth it? I don't know how many active users are left, but removing Ambient entirely might be disruptive to those used to it. If we don't want multiple themes, what's the point of even having a theme system? (user-maintained themes seems unlikely since they can break at any time during development)

I would keep ambient at least for the coming release, since it's not really any effort at the moment. If during continued development it becomes too much work to support two themes, we could still drop it.

**Comment by Jiiniasu** [comment]
One of the issues I see with having multiple themes is that the party modes sort of have their own theme, but still not. They have their own xml files for the screens, but they use the skin resources from the theme in use. This issue applies basically any theme and its design consistency throughout the game... One will have to decide which theme (if any) will dictate the look of the party modes.

When I've been developing Genius as a separate theme I had made the decision to simply ignore the party modes as they would always look weird and deviating. (I and the people I play with only use the regular singing mode anyway. =P)

I believe that the theming will need some enhancements before multiple themes can truly work side-by-side without looking odd.

I don't mind the idea of keeping Ambient, but it would trigger my OCD if the party modes makes one or both inconsistent in design style. =P

**Comment by flokuep** [comment]
You could add a Genius theme for every partymode. Default is just a fallback (and uses current theme colors and resources, so developing there doesn't cost so much time)...

**Comment by Jiiniasu** [comment]
@flokuep Huh, the more you know... I'll have to try it out. If it works like that it would be fine having both themes side by side.

**Comment by Jiiniasu** [comment]
I've added Genius Theme files to the Party modes and reverted the Default fallback theme. If we want to include Ambient it is only a matter of reverting https://github.com/Vocaluxe/Vocaluxe/pull/256/commits/d7807844aa017be37c9780384cf93abefd9a822b as well.

I'm still not too fond of the theming of the party modes as they use parts of screensong and got elements not using the positions of the xml-files, but at least specific theme files for the theme is a step to the right direction.

**Comment by flokuep** [comment]
Maybe I could help you :) There may be some jokers in ScreenSong, more I can't remember...

**Comment by askusbloodfist** [comment]
Genius imo if a beautifull work. Should be Default or part of the main pack imo GREAT WORK !

**Comment by flokuep** [comment]
After merging your note bar changes, there are conflicts now ;) Also, you could think about rating bars. I'm currently working on these, need them for 'Hold the line' game mode...

**Comment by Jiiniasu** [comment]
I'll have a crack on the conflicts. Now I can also update the Genius notes to the latest ones. =P

Could you describe what you mean with rating bars?

**Comment by flokuep** [comment]
https://psmedia.playstation.com/is/image/psmedia/SingStarPopEdition_sc0021?$MediaCarousel_Original$

The green thing  just beyond the points... And there will be a big red X that is shown if a player is _out_,

**Comment by Jiiniasu** [comment]
Ah, I guess I could just alter one of the existing assets to make a rating bar if such asset is needed.

I think I resolved the conflicts. Needed a second try because I'm such a git noob. =P

**Comment by flokuep** [comment]
Thanks, I will review this (after ci build is done).

**Comment by Jiiniasu** [comment]
Noticed I missed a few things, so hang on a bit more...

**Comment by Jiiniasu** [comment]
I believe it should be fine now. =)

**Comment by flokuep** [comment]
Thanks. There is still a problem:

- PartyModes doesn't work. There seem to be some wrong versions (see error.log)

And I've some suggestions 😅 

- Contrast between selected and not selected values in select slides is maybe a little bit slight... It's sometimes hard to identify selected value. 
- It's a bit hard to read options of song menu in song screen. A bit less transparency could work here.
- Could you spend a little bit work on cover theme again? It's not really colorful. Maybe add option to display cover? And coloring it a bit?
- Song menu could be improved a bit generally imho. I really like the black bar on top of most screens. It could also work on song screen for showing select song I guess. (maybe a bit more like name selection?) Maybe you could increase size of song info part to the full height. We could show some more informations here if you like (year, highscore?)
- Playlist control need really a lot of space, maybe use the same size as on name selection, I guess you could use some coloring there?
- I really like name selection, sing screen and score screen  😍 

Thanks for your work! @lukeIam I'd like to merge this and after that do some improvements because I need to add some elements to screens and don't like to do this twice.

**Comment by lukeIam** [comment]
@flokuep I'm not the theme expert - but as log as we are not breaking things you can merge this and improve the other points later (the nightly build is a development snapshot and must not be perfect)

**Comment by flokuep** [comment]
We should put theme videos into a package again I guess, and we need to update installer. But this can be done later.

**Comment by Jiiniasu** [comment]
Addressed the version errors in the log and did some colour adjustments.

Regarding the song menu and playlist size I've had ideas on redesigning the song menu and make space for highscore display etc. Although that would have to come in a separate PR or this one might get really, really old by the time I manage to realise such a redesign. =p

Kinda dry on ideas on the cover theme at the moment, but will try give it a ponder. If you've got any more specific ideas I'll gladly hear you out.

**Comment by flokuep** [comment]
Thanks. I will do another test, and if everything is fine, I'll merge.

**Comment by lukeIam** [comment]
just a note: At least for me the new background video is really slow lagging

**Comment by Jiiniasu** [comment]
@lukeIam That's interesting. It runs fine on one of my weakest laptops (Intel Core i5 520M with the built in Intel HD Graphics). Although I do remember having issues with lag when I ran a debug build on a quite powerful machine in the beginning of the year... Worked fine with a release build though.

But the issue you have is isolated to the background video?

**Comment by lukeIam** [comment]
@Jiiniasu 
I have also an Intel HD4000 integrated GPU.
The test was done with a release build.
Other music videos play fine (also the old theme video was perfectly smooth after ~1sec)

Working music video of a song:
working

**Comment by Jiiniasu** [comment]
@lukeIam The reason is most likely differences in bitrate and resolution. You can try [this file](https://github.com/Vocaluxe/Vocaluxe/files/1290494/BG_Video.zip) of which I have tried to match resolution and bitrate of the Ambience videos.

I noticed now that the files I made for Genius are with quite high bitrates. Perhaps I should render new files with different settings than I had originally used...

**Comment by lukeIam** [comment]
> I noticed now that the files I made for Genius are with quite high bitrates.

That could be a reason 😉 

> You can try this file of which I have tried to match resolution and bitrate of the Ambience videos.

Working 👍 
But we don't have to adjust our videos to fit my CPU in power saver mode 😆 
We just should agree on a good ratio between quality an performance.

By the way: ( @Jiiniasu @flokuep )
we should not put big binary files (like videos) to git. If there are any changes to those files they are stored twice and blow up the size our git repository (even if we delete the files later, they stay in the history)

**Comment by flokuep** [comment]
Yes, I've missed this.. Could you add it as nuget-package?

**Comment by Jiiniasu** [comment]
I'll prepare some new renders and run them through a proper encoder (x264). Please let me know how/where these should be stored to prevent the bloating of the repository.

**Comment by lukeIam** [comment]
> Please let me know how/where these should be stored to prevent the bloating of the repository.

Just put the videos into a zip (with a folder Structure like `Themes\Genius\video.mp4`) and put it here:
https://github.com/lukeIam/VocaluxeDependencies/tree/master/zips/themes

I will create a small nuget packet which downloads the files from there (if they do not exist locally).

**Comment by lukeIam** [comment]
BTW: Should I remove the Ambient theme from the build or do we keep it?

**Comment by flokuep** [comment]
We could remove it.

**Comment by Jiiniasu** [comment]
Encoded some videos in 1280x720 at 60 fps that can be tested.
Link: [Genius-Videos-720p60.zip](https://github.com/Vocaluxe/Vocaluxe/files/1293841/Genius-Videos-720p60.zip)

What do you think?

**Pull request merged**
