### PR TITLE
Multichannel recording

### PR DESCRIPTION
**Pull request by Jiiniasu**
Hi,

Been working on adding support for devices with more than two input channels (audio interfaces and such). What do you think? 

Description:
Support for "unlimited" amount of channels per recording device.
Upped ScreenOptionsRecord version and added neccessary lines to be able to configure n channels per device.
Added language strings for Player 1-6.

Tested successfully on a machine running Windows 10 with Tascam US-16x08 audio interface and Singstar Wireless Microphones used simultaneously.

16chscreen

2chscreen

### CODE REVIEW

**Comment by flokuep** [comment]
Thanks for your work! I really like this, your code looks nice too, so :+1: for merging!
Just a minor thing: Please increase ScreenVersion in ScreenOptionsRecord.xml!

**Comment by Jiiniasu** [comment]
Hi,
Good catch. Must have forgotten to increase the version when I replicated the changes from my own theme.

The change has been made.

**Comment by lukeIam** [comment]
@Jiiniasu thanks for your work!

I tested with one stereo and one mono mic - everything was working as expected.
:+1: for merging

**Comment by flokuep** [comment]
@Jiiniasu Everything ready for merging?

**Comment by Jiiniasu** [comment]
I believe everything should be ready to merge as I have not found any issues and not made any changes since 3a6ed62.

**Pull request merged**
