### PR TITLE
Use new acinerella and ffmpeg (3.2) versions

### LINKED ISSUE #241: Sporadic crashes when loading video
Hello.

This is probably the source of the crashes reported in #206.

In one of my branches I've (in the most ugly way) made a custom build for a LANparty where one of the modifications was instant previews when browsing (removing the need of pressing enter to start preview of song). This lead to more frequent crashing of Vocaluxe logging the error **Error opening video file (can't find decoder): <filename>**.

I've been digging a bit and have come to the following conclusion:

Below line somehow, sometimes, seemingly at random, throws a nullReferenceException. Occasionally, it can be recovered by running the same line again. Other times, it won't.

`decoder = (SACDecoder)Marshal.PtrToStructure(_Videodecoder, typeof(SACDecoder));`
(https://github.com/Vocaluxe/Vocaluxe/blob/develop/Vocaluxe/Lib/Video/Acinerella/CDecoderThread.cs#L277)

**Edit:** The _Videodecoder variable also seemed to have a valid pointer when it crashes. All I can say is that it wasn't 0.

Have anyone got any ideas on how to figure out a solution for this bug or any plausable theories on why this happens?

This crash has been observed mostly during previews when browsing songs, but has also occurred as early as when loading the intro videos.

### PR DESCRIPTION
**Pull request by lukeIam**
Updated the acinerella code * to support ffmpeg 3.2+ and adjusted the integration into Vocaluxe (manged wrapper).

Should give us some more speed and it seems that it also fixes #241 (and #206)

\* Rewrote some of already existing functions, because of at that time nobody knew where the source of our acinerella modification was.

### CODE REVIEW

**Comment by lukeIam** [comment]
@derivator Can you check the new versions on Linux please? (I've updated Vocaluxe/Lib/Video/Acinerella/acinerella.(h|c) )

**Comment by lukeIam** [comment]
I finally failed to satisfy the runtime dependencies with Ubuntu 12.04 ...

**Comment by lukeIam** [comment]
I really tried to test this under Linux and invested many days trying to get (normal) Vocaluxe running with Linux - without success.
I'm at the point I suggest to not longer hold back this PR and making the way free for the release (and for all those new features PRs waiting for post release time).

I don't think that this PR will break Linux support and there are not that many Vocaluxe-Linux users as the entry barrier is high.

**Comment by lukeIam** [comment]
@flokuep @derivator I would like to merge this PR to prepare a release.

**Comment by derivator** [comment]
@flokuep If I remember correctly, it should *run* fine on linux, if your distro ships a recent enough ffmpeg so you can build it at all...

**Comment by flokuep** [comment]
@derivator Okay, sounds nice. I've tried it multiple times without success, but okay ;)

@lukeIam I guess you could merge it.

**Pull request merged**
