### PR TITLE
[Design] Improvements and fixes

### LINKED ISSUE #354: Change guest profiles
Currently we have three guest profiles with very boring names: 'Guest 1', 'Guest 2' and 'Guest 3'.

I suggest to change them to some (un)real names and add maybe some nice avatars (a set of selectable avatars would also be nice, imho). It would be a good idea to have guest profiles for every difficulty, we may can find some nice names (male and female?) that reflects them (something like Betty Beginner).

Would be nice to have some help for designing avatars and getting some names.

### PR DESCRIPTION
**Pull request by marwin89**
### What does this PR do?
- **Add new textures for rap notes**
Rap notes will look more like blocks in contrast to round singing notes
- Remove duplicate Texture LogoMain--
- Removed duplicate covers from genius theme
- Add rating pop up texture
- update tonehelper texture
- update vocaluxe app icon
- update installer graphics dialog and banner
- **improved ui of profile screen**
reduce information overload, rearrange avatar meaningfully, now its potentially more space for player select field with more avatars on the left side (similiar to name select screen) (if slider descriptions would be moved closer to sliders)
- update time line (normal+expanded) to small modern look
- update pointsbarBG (sliced bar)
- update Party Mode Screen UI (simplifying centering)
- upload note textures source graphics (svg) `vocaluxe > ressources`
- Add new avatars, renaming files, rework of GuestAvatars (photorealistic avatar style is kinda transition till I can find or produce cartoonic material legally safe) (see [Style Guidlines for Vocaluxe](https://www.open-music-games.org/community/meet-the-teams#guide-for-artists))

### Motivation
- boost rap note support feature #479 
- boost pop up rating feature #270 
- clean up
- boost new installer #341 
- solve #354 
- improve user experience

### PR Status / Progress
✅ Draft PR > ✅ discussion > ✅ review > ✅ ready merge > merged

### QA
Changes are tested on Windows 10 and Windows 11 successfully ✅
No translation needed ✅ 
No special code review needed ✅ 

### Screenshot
New profile screen
Screenshot 2024-01-18 221323
Finetuning sing screen
SingScreenImprovement
Sliced pointsbar
ImprovePointsBarBG
Improved Party Mode Selection Screen
UpdatePartyModeScreen
New Avatars, New Guest Profiles
vocaluxe-2024-profile-avatars

### CODE REVIEW

**Comment by marwin89** [comment]
when this pull req is merged the Profile screen can get a sidebar for easy player browsing.
There has to be only some small coding (estimation: Small)
Hit me up via another pr, I'll do the layouting
ProfileScreenWithSelectSidebar

**Comment by marwin89** [comment]
Hi @flokuep , do you agree with all these changes? hope you enjoy - It's quite a lot of different stuff 🙂 🚀 
For me it's fine in general, (just not sure with sliced points bar). All tested on win10/win11 successfully. Have a nice day, would be nice to have a review till end of january 🙏🏻

**Review by flokuep — CHANGES_REQUESTED** [review]
Thank you for improving the design! I have just two smaller things that should be changed before merging
- You've added a licence file as docx-file. Please change to a non-binary file like markdown or simple text-file.
- The screen-version is mainly used for breaking-changes, not for design-changes. E.g. if a new screen element is added and used within code, we bump the screen-version within the code. During theme-loading, vocaluxe checks if all screen-version of the loaded screen are matching the in-code versions. If not, the theme wouldn't be loaded, because it might be incompatible. For your changes, bumping the version and adjusting the changeloh is not necessary.

**Comment by marwin89** [comment]
@flokuep thanks for review and qa
- license file is converted to markdown format ✅ 
- recovered original screen versions ✅

**Review by flokuep — APPROVED** [review]

**Pull request merged**
